# Generated by Django 3.1.3 on 2020-11-25 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=50, verbose_name='날짜')),
                ('cafeteria', models.CharField(max_length=50, verbose_name='식당')),
                ('menu', models.TextField(verbose_name='메뉴')),
            ],
            options={
                'verbose_name': '식단등록',
                'verbose_name_plural': '식단등록',
                'db_table': 'check',
            },
        ),
    ]
